# Generated by Django 4.1.6 on 2023-02-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(blank=True, max_length=140, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('features', models.JSONField()),
                ('tech_used', models.JSONField()),
                ('proj_image_preview', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('project_git_link', models.URLField()),
                ('project_other_link', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text', models.TextField(blank=True, max_length=140, null=True)),
                ('intro_text', models.TextField(blank=True, max_length=500, null=True)),
                ('about_me_intro1', models.TextField(blank=True, max_length=500, null=True)),
                ('about_me_intro2', models.TextField(blank=True, max_length=500, null=True)),
                ('recent_tech_used', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=140, null=True)),
                ('employer', models.CharField(blank=True, max_length=140, null=True)),
                ('employement_date', models.CharField(blank=True, max_length=140, null=True)),
                ('experience_descriptions', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
