# Generated by Django 4.1.6 on 2023-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myexperiences',
            name='experience_descriptions',
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions10',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions3',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions4',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions5',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions6',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions7',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions8',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myexperiences',
            name='experience_descriptions9',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
