# Generated by Django 4.1.6 on 2023-02-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0003_myexperiences_css_class_myexperiences_css_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexperiences',
            name='css_class',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myexperiences',
            name='css_id',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
