# Generated by Django 4.1.6 on 2023-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0005_alter_myexperiences_css_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexperiences',
            name='css_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myexperiences',
            name='css_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
