# Generated by Django 4.1.6 on 2023-02-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0007_remove_myprojects_features_myprojects_features1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myintro',
            name='recent_tech_used',
        ),
        migrations.AddField(
            model_name='myintro',
            name='tech_used1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myintro',
            name='tech_used2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myintro',
            name='tech_used3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myintro',
            name='tech_used4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myintro',
            name='tech_used5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
