# Generated by Django 4.1.6 on 2023-02-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0008_remove_myintro_recent_tech_used_myintro_tech_used1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myintro',
            name='head_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
