# Generated by Django 4.1.6 on 2023-02-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0009_alter_myintro_head_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='myintro',
            name='tech_used6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
