# Generated by Django 4.1.6 on 2023-02-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0011_alter_myintro_tech_used1_alter_myintro_tech_used2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myintro',
            name='my_email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='myintro',
            name='my_linkedIn',
            field=models.URLField(blank=True, max_length=70, null=True),
        ),
    ]
