# Generated by Django 4.1.6 on 2023-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0012_myintro_my_email_myintro_my_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myintro',
            name='my_gitHub',
            field=models.URLField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='myintro',
            name='my_instagram',
            field=models.URLField(blank=True, max_length=70, null=True),
        ),
    ]
