# Generated by Django 4.1.6 on 2023-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_App', '0013_myintro_my_github_myintro_my_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='myintro',
            name='my_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
